# SPDX-FileCopyrightText: Copyright (c) 2022 Anton Shatokhin
# SPDX-License-Identifier: MIT

.PHONY: build clean

all: build

build:
	eoc --parser 0.61.3 --home-tag 0.61.3 --easy dataize life cycle 0

clean:
	rm -rf .eoc/
